"""profile_endpoints management command"""

import time

from django.conf import settings
from django.core.management.base import BaseCommand, CommandError
from django.db import connection
from django.test.utils import CaptureQueriesContext

from rest_framework.test import APIClient

from core import models

from demo import defaults

ITEMS_URL = f"/api/{settings.API_VERSION}/items/"
USERS_URL = f"/api/{settings.API_VERSION}/users/"
LIST_PARAMS = "ordering=-type,title&page_size=200"
# A common last name among the users generated by create_perf_dataset
USER_SEARCH = "martin"


class Command(BaseCommand):
    """
    Call the main API endpoints as a given user and report their response time,
    their SQL queries and, optionally, the execution plan of their slowest query.
    """

    help = __doc__

    def add_arguments(self, parser):
        """Add arguments to choose the user and what to report."""
        parser.add_argument(
            "-f",
            "--force",
            action="store_true",
            default=False,
            help="Force command execution despite DEBUG is set to False",
        )
        parser.add_argument(
            "--email",
            default=defaults.DEV_USERS[0]["email"],
            help="Email of the user performing the requests",
        )
        parser.add_argument(
            "--user-id",
            help="Id of the user performing the requests, takes precedence over --email",
        )
        parser.add_argument(
            "--item",
            action="append",
            default=[],
            help="Id of an extra folder to list the children of, can be repeated",
        )
        parser.add_argument(
            "--only",
            action="append",
            default=[],
            help="Only profile the endpoints whose label starts with this value, can be repeated",
        )
        parser.add_argument(
            "--repeat",
            type=int,
            default=3,
            help="Number of calls per endpoint, the first one warms up the caches",
        )
        parser.add_argument(
            "--slowest",
            type=int,
            default=3,
            help="Number of slowest queries to display per endpoint",
        )
        parser.add_argument(
            "--explain",
            action="store_true",
            default=False,
            help="Display the EXPLAIN (ANALYZE, BUFFERS) of the slowest query of each endpoint",
        )
        parser.add_argument(
            "--no-jit",
            action="store_true",
            default=False,
            help="Disable the Postgres JIT compilation for the session",
        )

    def handle(self, *args, **options):
        """Handling of the management command."""
        if not settings.DEBUG and not options["force"]:
            raise CommandError(
                (
                    "This command is not meant to be used in production environment "
                    "except you know what you are doing, if so use --force parameter"
                )
            )
        lookup = {"pk": options["user_id"]} if options["user_id"] else {"email": options["email"]}
        try:
            user = models.User.objects.get(**lookup)
        except models.User.DoesNotExist as error:
            raise CommandError(f"No user found with {lookup}.") from error
        except models.User.MultipleObjectsReturned as error:
            raise CommandError(f"Several users found with {lookup}, use --user-id.") from error

        if options["no_jit"]:
            with connection.cursor() as cursor:
                cursor.execute("SET jit = off")

        client = APIClient()
        client.force_authenticate(user)

        for label, url in self.get_endpoints(user, options["item"]):
            if options["only"] and not label.startswith(tuple(options["only"])):
                continue
            self.profile(client, label, url, options)

    def get_endpoints(self, user, extra_item_ids):
        """Build the list of endpoints to call, with the folders the user can reach."""
        folder_ids = list(
            models.ItemAccess.objects.filter(
                user=user,
                item__type=models.ItemTypeChoices.FOLDER,
                item__path__depth=1,
                item__deleted_at__isnull=True,
            )
            .order_by("created_at")
            .values_list("item_id", flat=True)[:3]
        )
        other_user = models.User.objects.filter(is_active=True).exclude(pk=user.pk).first()
        email_search = other_user.email if other_user else "camille.martin@culture.test"

        endpoints = [
            ("list", f"{ITEMS_URL}?{LIST_PARAMS}"),
            ("recents", f"{ITEMS_URL}recents/?page_size=200"),
            ("favorites", f"{ITEMS_URL}favorites/?page_size=200"),
            ("trashbin", f"{ITEMS_URL}trashbin/?page_size=200"),
        ]
        endpoints += [
            (f"children {folder_id}", f"{ITEMS_URL}{folder_id}/children/?{LIST_PARAMS}")
            for folder_id in [*folder_ids, *extra_item_ids]
        ]
        endpoints += [
            ("users trigram", f"{USERS_URL}?q={USER_SEARCH}"),
            ("users levenshtein", f"{USERS_URL}?q={email_search}"),
            ("contacts", f"{USERS_URL}contacts/?q={USER_SEARCH}"),
        ]
        return endpoints

    def profile(self, client, label, url, options):
        """Call an endpoint several times and report on its last call."""
        durations = []
        for _index in range(max(1, options["repeat"])):
            with CaptureQueriesContext(connection) as context:
                start = time.perf_counter()
                response = client.get(url)
                durations.append((time.perf_counter() - start) * 1000)

        queries = sorted(context.captured_queries, key=lambda query: -float(query["time"]))
        sql_time = sum(float(query["time"]) for query in queries) * 1000
        self.stdout.write(
            self.style.MIGRATE_HEADING(f"\n{label} [{response.status_code}] {url}")
            + f"\n  calls: {', '.join(f'{duration:.0f}ms' for duration in durations)}"
            + f" | last call: {len(queries)} queries, {sql_time:.0f}ms in SQL"
        )
        for query in queries[: options["slowest"]]:
            self.stdout.write(f"  {float(query['time']) * 1000:>7.1f}ms  {query['sql'][:300]}")

        if options["explain"] and queries and queries[0]["sql"].lstrip().startswith("SELECT"):
            with connection.cursor() as cursor:
                cursor.execute(f"EXPLAIN (ANALYZE, BUFFERS) {queries[0]['sql']}")
                plan = "\n".join(f"    {row[0]}" for row in cursor.fetchall())
            self.stdout.write(f"  EXPLAIN of the slowest query:\n{plan}")
