# Generated by Django 5.2.3 on 2025-06-23 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_item_hard_deleted_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ('created_at',), 'verbose_name': 'Item', 'verbose_name_plural': 'Items'},
        ),
        migrations.RemoveConstraint(
            model_name='item',
            name='check_filename_set_for_files',
        ),
    ]
