# Generated by Django 5.1.9 on 2025-06-02 13:27

import django.db.models.deletion
import pgvector.django.vector
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_item_hard_deleted_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ('created_at',), 'verbose_name': 'Item', 'verbose_name_plural': 'Items'},
        ),
        migrations.CreateModel(
            name='TextChunk',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='primary key for the record as UUID', primary_key=True, serialize=False, verbose_name='id')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='date and time at which a record was created', verbose_name='created on')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='date and time at which a record was last updated', verbose_name='updated on')),
                ('text', models.TextField()),
                ('order', models.PositiveIntegerField()),
                ('embedding', pgvector.django.vector.VectorField(dimensions=1024)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.item')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
