# Generated by Django 5.1.9 on 2025-06-26 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_item_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='language',
            field=models.CharField(blank=True, choices=[('en-us', 'English'), ('fr-fr', 'French'), ('de-de', 'German')], default=None, help_text='The language in which the user wants to see the interface.', max_length=10, null=True, verbose_name='language'),
        ),
    ]
