# Generated by Django 5.2.4 on 2025-07-22 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_user_language'),
        ('malware_detection', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='upload_state',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('analyzing', 'Analyzing'), ('suspicious', 'Suspicious'), ('file_too_large_to_analyze', 'File too large to analyze'), ('ready', 'Ready')], max_length=25, null=True),
        ),
    ]
