# Generated by Django 5.2.4 on 2025-07-22 15:12

from django.db import migrations, models

def update_items_upload_state_value(apps, schema_editor):
    Item = apps.get_model('core', 'Item')
    Item.objects.filter(upload_state='uploaded').update(upload_state='ready')

def reverse_update_items_upload_state_value(apps, schema_editor):
    Item = apps.get_model('core', 'Item')
    Item.objects.filter(upload_state='ready').update(upload_state='uploaded')


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_item_upload_state'),
    ]

    operations = [
        migrations.RunPython(
            update_items_upload_state_value, reverse_code=reverse_update_items_upload_state_value
        ),
    ]
