# Generated by Django 5.2.8 on 2025-11-13 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_user_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='claims',
            field=models.JSONField(blank=True, default=dict, help_text='Claims from the OIDC token.'),
        ),
        migrations.AlterField(
            model_name='user',
            name='language',
            field=models.CharField(blank=True, choices=[('en-us', 'English'), ('fr-fr', 'French'), ('de-de', 'German'), ('nl-nl', 'Dutch')], default=None, help_text='The language in which the user wants to see the interface.', max_length=10, null=True, verbose_name='language'),
        ),
    ]
