# Generated by Django 5.2.9 on 2026-02-03 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_user_claims_alter_user_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='link_reach',
            field=models.CharField(blank=True, choices=[('restricted', 'Restricted'), ('authenticated', 'Authenticated'), ('public', 'Public')], max_length=20, null=True),
        ),
    ]
