# Generated by Django 5.2.11 on 2026-02-09 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_item_link_reach'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='short_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='short name'),
        ),
    ]
