# Generated by Django 5.2.8 on 2026-02-03 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_item_link_reach'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_release_note_seen',
            field=models.CharField(blank=True, max_length=85, null=True, verbose_name='last release note seen'),
        ),
    ]
