# Generated by Django 5.2.8 on 2026-02-25 00:19

from django.db import migrations
from django.db.models import F
from django.db.models.indexes import Index
from django_ltree.functions import NLevel


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0019_user_last_release_note_seen"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="item",
            index=Index(
                NLevel(F("path")),
                name="drive_item_path_nlevel_idx",
            ),
        ),
    ]
