# Generated by Django 5.2.11 on 2026-03-09 14:11

import core.models
import django.core.serializers.json
import django_pydantic_field.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_remove_item_numchild_path_nlevel_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='column_preferences',
            field=django_pydantic_field.fields.PydanticSchemaField(blank=True, config=None, default=None, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True, schema=core.models.ColumnPreferences),
        ),
    ]
