# Generated by Django 5.2.12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0020_remove_item_numchild_path_nlevel_idx"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="is_encrypted",
            field=models.BooleanField(
                default=False,
                help_text="Whether this item is encrypted (standalone file or part of an encrypted subtree).",
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="encrypted_symmetric_key",
            field=models.TextField(
                blank=True,
                help_text=(
                    "This item's symmetric key, wrapped (encrypted) by the parent folder's symmetric key. "
                    "NULL for encryption roots (standalone files or topmost encrypted folders, which use "
                    "per-user keys in ItemAccess instead) and for unencrypted items."
                ),
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="itemaccess",
            name="encrypted_item_symmetric_key_for_user",
            field=models.TextField(
                blank=True,
                help_text=(
                    "The accessed item's symmetric key, encrypted with this user's public key. "
                    "This is the user's entry point into the key chain."
                ),
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="itemaccess",
            name="encryption_public_key_fingerprint",
            field=models.CharField(
                blank=True,
                help_text=(
                    "Fingerprint of the user's public key at the time of sharing. "
                    "Used to detect key changes — if the user's current public key fingerprint "
                    "differs from this value, the access needs re-encryption."
                ),
                max_length=16,
                null=True,
            ),
        ),
    ]
