# Generated by Django 5.2.14 on 2026-05-26 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_user_column_preferences'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='numchild',
        ),
        migrations.RemoveField(
            model_name='item',
            name='numchild_folder',
        ),
        migrations.AlterField(
            model_name='item',
            name='upload_state',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('duplicating', 'Duplicating'), ('analyzing', 'Analyzing'), ('suspicious', 'Suspicious'), ('file_too_large_to_analyze', 'File too large to analyze'), ('ready', 'Ready')], max_length=25, null=True),
        ),
    ]
