# Generated by Django 5.2.12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0021_item_encryption_fields"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="itemaccess",
            name="encryption_public_key_fingerprint",
        ),
        migrations.AddField(
            model_name="itemaccess",
            name="encryption_public_key_version",
            field=models.PositiveIntegerField(
                blank=True,
                help_text=(
                    "Version of the user's encryption public key at the time of sharing. "
                    "Used to detect key changes — if the user's current public key version "
                    "differs from this value, the access needs re-encryption."
                ),
                null=True,
                verbose_name="encryption public key version",
            ),
        ),
    ]
