# Generated by Django 5.2.14 on 2026-07-08 09:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_alter_item_upload_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='storage_limit_override',
            field=models.BigIntegerField(blank=True, default=None, help_text='Storage limit in bytes for this user, used by the local entitlements backend. Leave empty to use the configured default limit. Set to 0 for unlimited storage.', null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='storage limit override'),
        ),
    ]
