# Generated by Django 5.2.14 on 2026-07-08 10:14

from django.contrib.postgres.operations import AddIndexConcurrently
from django.db import migrations, models


class Migration(migrations.Migration):

    # CREATE INDEX CONCURRENTLY cannot run inside a transaction. It avoids
    # locking writes on the item table while the index is being built.
    atomic = False

    dependencies = [
        ('core', '0025_user_storage_limit_override'),
    ]

    operations = [
        AddIndexConcurrently(
            model_name='item',
            index=models.Index(condition=models.Q(('hard_deleted_at__isnull', True)), fields=['creator'], include=('size',), name='item_creator_size_not_hdel_idx'),
        ),
    ]
