# Generated by Django 5.2.14 on 2026-07-24 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_item_item_creator_size_not_hdel_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Metadata describing an external resource this item points to.', null=True),
        ),
    ]
