# Generated by Django 5.2.15 on 2026-08-20 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_item_creator_size_quota_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='link_expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='link expiration date'),
        ),
        migrations.AddField(
            model_name='item',
            name='link_password',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='link password'),
        ),
    ]
