# Generated by Django 5.2.14 on 2026-07-24 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_item_creator_size_quota_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='is_restricted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name='item',
            constraint=models.CheckConstraint(condition=models.Q(('is_restricted', False), ('type', 'folder'), _connector='OR'), name='check_is_restricted_only_on_folders'),
        ),
    ]
