# Generated by Django 5.2.14 on 2026-07-24 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_item_creator_size_quota_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='target',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='restriction', to='core.item'),
        ),
        migrations.AlterField(
            model_name='item',
            name='type',
            field=models.CharField(choices=[('folder', 'Folder'), ('file', 'File'), ('restriction', 'Restriction')], default='folder', max_length=30),
        ),
        migrations.AddConstraint(
            model_name='item',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('type', 'restriction'), ('target__isnull', False)), models.Q(models.Q(('type', 'restriction'), _negated=True), ('target__isnull', True)), _connector='OR'), name='check_target_only_on_restrictions'),
        ),
    ]
