# Generated by Django 5.2.14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0030_item_add_restriction_target"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="is_encrypted",
            field=models.BooleanField(
                default=False,
                help_text=(
                    "Whether this item is encrypted (standalone file or part of an "
                    "encrypted subtree)."
                ),
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="encrypted_symmetric_key",
            field=models.TextField(
                blank=True,
                help_text=(
                    "This item's symmetric key, wrapped (encrypted) by the parent folder's "
                    "symmetric key. NULL for encryption roots (standalone files or topmost "
                    "encrypted folders, which use per-user keys in ItemAccess instead) and "
                    "for unencrypted items."
                ),
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="itemaccess",
            name="encrypted_item_symmetric_key_for_user",
            field=models.TextField(
                blank=True,
                help_text=(
                    "The accessed item's symmetric key, encrypted with this user's public "
                    "key. This is the user's entry point into the key chain."
                ),
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="itemaccess",
            name="encryption_public_key_version",
            field=models.PositiveIntegerField(
                blank=True,
                help_text=(
                    "Version of the user's encryption public key at the time of sharing. "
                    "Used to detect key changes: if the user's current public key version "
                    "differs from this value, the access needs re-encryption."
                ),
                null=True,
                verbose_name="encryption public key version",
            ),
        ),
    ]
