# Generated by Django 5.2.16 on 2026-09-03 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_item_link_expires_at_item_link_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='linktrace',
            name='link_unlocked_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='link unlocked at'),
        ),
    ]
